// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.19.4
// source: gpt/gpt.proto

package gpt

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GptMsgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=Query,proto3" json:"Query,omitempty"`
}

func (x *GptMsgRequest) Reset() {
	*x = GptMsgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gpt_gpt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GptMsgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GptMsgRequest) ProtoMessage() {}

func (x *GptMsgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gpt_gpt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GptMsgRequest.ProtoReflect.Descriptor instead.
func (*GptMsgRequest) Descriptor() ([]byte, []int) {
	return file_gpt_gpt_proto_rawDescGZIP(), []int{0}
}

func (x *GptMsgRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type GptMsgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reply string `protobuf:"bytes,1,opt,name=Reply,proto3" json:"Reply,omitempty"`
}

func (x *GptMsgResponse) Reset() {
	*x = GptMsgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gpt_gpt_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GptMsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GptMsgResponse) ProtoMessage() {}

func (x *GptMsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gpt_gpt_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GptMsgResponse.ProtoReflect.Descriptor instead.
func (*GptMsgResponse) Descriptor() ([]byte, []int) {
	return file_gpt_gpt_proto_rawDescGZIP(), []int{1}
}

func (x *GptMsgResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

var File_gpt_gpt_proto protoreflect.FileDescriptor

var file_gpt_gpt_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x67, 0x70, 0x74, 0x2f, 0x67, 0x70, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x25, 0x0a, 0x0d, 0x47, 0x70, 0x74, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x22, 0x26, 0x0a, 0x0e, 0x47, 0x70, 0x74, 0x4d, 0x73, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0x39,
	0x0a, 0x0c, 0x47, 0x70, 0x74, 0x4d, 0x73, 0x67, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x29,
	0x0a, 0x04, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x0e, 0x2e, 0x47, 0x70, 0x74, 0x4d, 0x73, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x47, 0x70, 0x74, 0x4d, 0x73, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1b, 0x5a, 0x19, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x69, 0x61, 0x2f, 0x70, 0x62, 0x2f, 0x67,
	0x70, 0x74, 0x3b, 0x67, 0x70, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gpt_gpt_proto_rawDescOnce sync.Once
	file_gpt_gpt_proto_rawDescData = file_gpt_gpt_proto_rawDesc
)

func file_gpt_gpt_proto_rawDescGZIP() []byte {
	file_gpt_gpt_proto_rawDescOnce.Do(func() {
		file_gpt_gpt_proto_rawDescData = protoimpl.X.CompressGZIP(file_gpt_gpt_proto_rawDescData)
	})
	return file_gpt_gpt_proto_rawDescData
}

var file_gpt_gpt_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gpt_gpt_proto_goTypes = []interface{}{
	(*GptMsgRequest)(nil),  // 0: GptMsgRequest
	(*GptMsgResponse)(nil), // 1: GptMsgResponse
}
var file_gpt_gpt_proto_depIdxs = []int32{
	0, // 0: GptMsgSender.Send:input_type -> GptMsgRequest
	1, // 1: GptMsgSender.Send:output_type -> GptMsgResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gpt_gpt_proto_init() }
func file_gpt_gpt_proto_init() {
	if File_gpt_gpt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gpt_gpt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GptMsgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gpt_gpt_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GptMsgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gpt_gpt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gpt_gpt_proto_goTypes,
		DependencyIndexes: file_gpt_gpt_proto_depIdxs,
		MessageInfos:      file_gpt_gpt_proto_msgTypes,
	}.Build()
	File_gpt_gpt_proto = out.File
	file_gpt_gpt_proto_rawDesc = nil
	file_gpt_gpt_proto_goTypes = nil
	file_gpt_gpt_proto_depIdxs = nil
}
